// This file was generated by the Finch-Resources module. Do not edit it directly.
package {{ .Pkg }}

import "github.com/adm87/finch-resources/resources"

{{- $byRoot := (include "byRoot" .Manifest) | fromYaml }}

const (
{{- range $root, $metadata := $byRoot }}
{{ include "section.header" $root | indent 4 }}
{{"\n"}}
{{- range $item := $metadata }}
{{ include "section.item" $item | indent 4 }}
{{- end }}
{{"\n"}}
{{- end }}
)

{{- define "byRoot" -}}
{{- $m := map -}}
{{- range $key, $value := . -}}
{{- $root := from $value "root" -}}
{{- $value = set $value "name" $key -}}
{{- $metadata := (from $m $root) | ifNil array -}}
{{- $metadata = append $metadata $value -}}
{{- $m = merge $m (map $root $metadata) -}}
{{- end -}}
{{- toYaml $m -}}
{{- end -}}

{{- define "section.header" -}}
// ======================================================
// {{ . | capitalize }}
// ======================================================
{{- end -}}

{{- define "section.item" -}}
{{- $doc := printf "%s" .root -}}
{{- $path := .path | ifNil "" -}}
{{- if ne $path "" -}}
{{- $path = trim $path "/" -}}
{{- $doc = printf "%s/%s" $doc $path -}}
{{- end -}}
{{- $doc = printf "%s/%s.%s" $doc .name .type -}}
{{ .name | pascal }} resources.ResourceHandle = "{{ .name }}" // {{ $doc }}
{{- end -}}