// This file was generated by the Finch-Resources module. Do not edit it directly.
package {{ .Pkg }}

{{- $byRoot := (include "byRoot" .Manifest) | fromYaml }}

type ResourceKey string

const (
{{- range $root, $metadata := $byRoot }}
{{ include "section.header" $root | indent 4 }}
{{- range $item := $metadata }}
{{ include "section.item" $item | indent 4 }}
{{- end }}
{{- end }}
)

{{- define "byRoot" -}}
{{- $m := map -}}
{{- range $key, $value := . -}}
{{- $root := from $value "root" -}}
{{- $value = set $value "name" $key -}}
{{- $metadata := (from $m $root) | ifNil array -}}
{{- $metadata = append $metadata $value -}}
{{- $m = merge $m (map $root $metadata) -}}
{{- end -}}
{{- toYaml $m -}}
{{- end -}}

{{- define "section.header" -}}
// ======================================================
// {{ . | capitalize }}
// ======================================================
{{- end -}}

{{- define "section.item" -}}
{{ .name | pascal }} ResourceKey = "{{ .name }}"
{{- end -}}